variables:
    APT_CACHE_DIR: apt-cache

cache:
    key: apt-cache
    paths:
    - apt-cache/
    - cargo/
    - target/

before_script:
    - mkdir -pv $APT_CACHE_DIR
    - apt-get -qq update && apt-get -o dir::cache::archives="$APT_CACHE_DIR" -qq -y install libudev-dev pkg-config

test:1.13:
    image: "scorpil/rust:1.13"
    script:
    - cargo build --verbose

test:stable:
    image: "scorpil/rust:stable"
    script:
    - cargo build --verbose

test:beta:
    image: "scorpil/rust:beta"
    script:
    - cargo build --verbose

test:nightly:
    image: "scorpil/rust:nightly"
    script:
    - cargo build --verbose
